### ISSUE TITLE
PatchSegment Doesn't Support Semantic Patching

### ISSUE THREAD

**Issue by kwalsh-rz** [launchdarkly/api-client-go#14]
Does PatchSegment not support semantic patching? The documentation states that it does but I don't see the operations allowed. Am I misunderstanding?  How would I accomplish removing an `includedTarget` through a JSON patch?

**Comment by mmrj** [comment]
Hi @kwalsh-rz , thanks for reaching out. Yes, the `patchSegment` endpoint supports semantic patching, and the operations are hidden in a "twistie" here, https://apidocs.launchdarkly.com/tag/Segments#operation/patchSegment: 

<img width="867" alt="patch segment - click to expand instructions" src="https://github.com/launchdarkly/api-client-go/assets/1653043/40725a7e-e549-49a5-85da-63e427f4131a">

To remove an included target, you can use the `removeIncludedTargets` instruction.

**Comment by kwalsh-rz** [comment]
Thanks for the quick response. I'm still not fully understanding though. PatchSegment doesn't support `RequestBody` the way other methods do, so how do you put the request through?

**Comment by mmrj** [comment]
There are a couple of things going on here:

* While many of our endpoints support both semantic patch and JSON patch, when they do support both, one format is privileged. This means, among other things, that the "Try it" panel on apidocs.launchdarkly.com and the generated client libraries use that format.
* Unfortunately, we don't currently support both semantic patch and JSON patch formats for a given endpoint in the client libraries, including the Go library. (Background: We haven't yet added support for `anyOf` to our OpenAPI generator, which would allow multiple request schemas.) 
* That said, here are the request bodies for removing included targets:

```
// semantic patch
// remember to append ';domain-model=launchdarkly.semanticpatch' 
// to your 'Content-type' header if using this
{
  "instructions": [{
    "kind": "removeIncludedTargets",
    "contextKind": "user",
    "values": [ "sandy" ]
  }]
}
```

```
// json patch
{
  "patch": [
    {
      "op": "remove",
      "path": "/included/0" 
// this is a 0-indexed array of the included targets,
// so recommend doing a 'getSegment' first to examine the 'included' array 
// and make sure you're removing the correct target
    }
  ]
}
```

Apologies for any confusion on this. I initially read your question as being just about finding semantic patch info in the docs and jumped in that direction without providing more background. Let me know if you have any additional questions.

**Comment by kwalsh-rz** [comment]
Thanks!  That clears up part of my confusion, but I still don't understand how I would send across your examples above using the existing clients. How do you send a generic request body across to `PatchSegment`?  It doesn't support it. Are you saying we just can't do this with the Go client?

**Comment by kwalsh-rz** [comment]
I solved this by first calling `GetSegment` and figuring out the index of the items that I want to remove. I then used those values in the `path` of the patch segment. It's not as easy as semantic patching would have been but it works

**Comment by lucywyman** [comment]
Hi @kwalsh-rz! We definitely recommend using semantic patches for adding or removing targets ([from the docs](https://apidocs.launchdarkly.com/tag/Segments#operation/patchSegment): To add or remove targets from segments, we recommend using semantic patch.) You can use a `PatchSegmentInstruction` object to send a semantic patch to the Segments API, something like this (copied from [this example](https://github.com/launchdarkly/api-client-go/blob/main/docs/SegmentsApi.md#example-8)) *should* work:
```
package main

import (
    "context"
    "fmt"
    "os"
    openapiclient "./openapi"
)

func main() {
    projectKey := "projectKey_example" // string | The project key
    environmentKey := "environmentKey_example" // string | The environment key
    segmentKey := "segmentKey_example" // string | The segment key
    patchSegmentRequest := *openapiclient.NewPatchSegmentRequest([]openapiclient.PatchSegmentInstruction{*openapiclient.NewPatchSegmentInstruction("removeIncludedTargets", "ContextKind_example", "my_target")})

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)
    resp, r, err := apiClient.SegmentsApi.PatchExpiringTargetsForSegment(context.Background(), projectKey, environmentKey, segmentKey).PatchSegmentRequest(patchSegmentRequest).Execute()
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error when calling `SegmentsApi.PatchExpiringTargetsForSegment``: %v\n", err)
        fmt.Fprintf(os.Stderr, "Full HTTP response: %v\n", r)
    }
    // response from `PatchExpiringTargetsForSegment`: ExpiringTargetPatchResponse
    fmt.Fprintf(os.Stdout, "Response from `SegmentsApi.PatchExpiringTargetsForSegment`: %v\n", resp)
}
```
