### ISSUE TITLE
How to pass the access token?

### ISSUE THREAD

**Issue by asaha-atlassian** [launchdarkly/api-client-go#5]
Hi, I tried the following for making an API request, but getting a 401:

```
c := ldClient.NewConfiguration()
client := ldClient.NewAPIClient(c)

ctx := context.Background()
ctx = context.WithValue(ctx, ldClient.ContextAPIKey, "accesstoken")
flags, _, err := client.FeatureFlagsApi.GetFeatureFlags(ctx, "myprojectname", nil)
```
Is this the right way to do it?

**Comment by bwoskow-ld** [comment]
Hi @asaha-atlassian ,

Rather than using a `ContextAPIKey` you'll want [`ContextAccessToken`](https://github.com/launchdarkly/api-client-go/blob/master/configuration.go#L35). Right now you're getting a 401 because you're specifying your access token value while identifying it as an API key.

Let me know if that resolves your issue.

Cheers,
@bwoskow-ld

**Comment by asaha-atlassian** [comment]
Thanks, i *think*, i am now failing to set the environment correctly. This is my go code:

```
c := ldClient.NewConfiguration()
	client := ldClient.NewAPIClient(c)
	o := ldClient.FeatureFlagsApiGetFeatureFlagsOpts{
		Env: optional.NewInterface("test"),
	}

	ctx := context.Background()
	ctx = context.WithValue(ctx, ldClient.ContextAccessToken, "api-key")
	flags, _, err := client.FeatureFlagsApi.GetFeatureFlags(ctx, "proj-name", &o)
```

The same API key works with Python HTTP client. For comparison:

```
def get_all_features(config):
    url = "%s" % BASE_URL
    headers = {'Content-type': 'application/json', 'Authorization': 'api_key %s' % config['api_key']}
    querystring = {"env": environment}
    r = requests.get(url, headers=headers, params=querystring)
    if not r.status_code == 200:
        print('ERROR: Failed to retrieve all feature flags. Error: (%s) %s' % (r.status_code, r.reason))
        print(r.content)
    return r.json()
```

Do you see anything obviously wrong?

**Comment by bwoskow-ld** [comment]
Per [this comment](https://github.com/launchdarkly/api-client-go/blob/master/api_feature_flags.go#L1383) try providing the environment as an array with `"test"` as the sole value.

Also in case you missed it, there's some [sample code](https://github.com/launchdarkly/api-client-go#sample-code) in the repository readme.

**Comment by asaha-atlassian** [comment]
Thank you @bwoskow-ld - got it working. Key pieces:
```
o := ldClient.FeatureFlagsApiGetFeatureFlagsOpts{
		Env: optional.NewInterface([]string{"test"}),
	}

	ctx := context.Background()
	ctx = context.WithValue(
		ctx,
		ldClient.ContextAPIKey,
		ldClient.APIKey{
			Key: "api-lkey",
		},
	)
```
