### ISSUE TITLE
Make the sample code more discoverable

### ISSUE THREAD

**Issue by asaha-atlassian** [launchdarkly/api-client-go#6]
While facing a problem in #5 - I was pointed to the sample code in the README. However, due to the fact that we have the reference docs way before that and as we always are trying to get our own code working asap, I ignored that README beyond a few scrolls. 

Is the README.md also auto-generated or can I make a PR to the README itself?

**Comment by bwoskow-ld** [comment]
You can't PR the readme in this repository as it'll be overridden with the next release.

If you want to take a look at how the readme is generated though, you can pop over to https://github.com/launchdarkly/ld-openapi/blob/master/Makefile#L142. There you'll see how we construct the eventual README.md's contents. Lines 144-149 are where the sample code get added to the end.

**Comment by asaha-atlassian** [comment]
Thanks, looks like there is a good reason to have the sample at the end. It is appending to the generated README.md.

**Comment by asaha-atlassian** [comment]
I will close this since i have now created a PR there.
