### ISSUE TITLE
Fix go.mod file for v6

### ISSUE THREAD

**Issue by szechyjs** [launchdarkly/api-client-go#8]
`module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v6`

Please add the correct version to the module file.

**Comment by carmenquan** [comment]
Hi @szechyjs,

Thanks for bringing this to our attention - we'll address this in our next release!

Carmen

**Comment by carmenquan** [comment]
Hi @szechyjs,

We addressed this feedback in our latest release. https://github.com/launchdarkly/api-client-go/releases/tag/v7.0.0
If you have additional questions, please re-open this or file a new issue.

Thank you!
Carmen
