### ISSUE TITLE
Rule.variation is required

### ISSUE THREAD

**Issue by szechyjs** [launchdarkly/api-client-go#9]
When creating a patch that includes a `Rule` the marshalled result fails to include `Variation` if its value is `0` due to `omitempty`.

https://github.com/launchdarkly/api-client-go/blob/master/model_rule.go#L21

This was the first instance of this that I came across, but I'm sure there are other required fields that get omitted with zero values.

**Comment by InTheCloudDan** [comment]
Hi @szechyjs do you happen to have a minimal reproducible sample of code for it? The `Rule` struct is a pointer to an `int32` so even if it's 0 it should be getting marshalled.

**Comment by sloloris** [comment]
Going to go ahead and close this issue as it is quite old - if this problem persists, or you encounter any others, please file a new one!
